global:
  scrape_interval: 15s # How often to scrape targets
  evaluation_interval: 15s # How often to evaluate rules

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'aams-not-found'
  static_configs:
  - targets: ['aams-not-found.onrender.com:443']
  scheme: https
