global:
  scrape_interval: 15s # How often to scrape targets
  evaluation_interval: 15s # How often to evaluate rules

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'nodejs-app'
  static_configs:
  - targets: ['localhost:3000'] # Replace with your Node.js app's metrics endpoint
