global:
  scrape_interval: 15s # How often to scrape targets
  evaluation_interval: 15s # How often to evaluate rules

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'aams-not-found'
  static_configs:
  - targets: ['aams-nfound.onrender.com:443']
  scheme: https

- job_name: 'personal-cloud'
  static_configs:
  - targets: ['aams-personal-cloud.onrender.com:443']
  scheme: https

- job_name: 'aams-blog-app'
  static_configs:
  - targets: ['aams-blog-app.onrender.com:443']
  scheme: https
