# Exported from Render on 2024-09-09T18:03:29Z
services:
- type: web
  name: aams-adminer
  runtime: docker
  repo: https://github.com/ahmedamsoliman-1/ahmedamsoliman-1
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  rootDir: docker/docker-apps/adminer
- type: web
  name: aams-redis-commander
  runtime: docker
  repo: https://github.com/ahmedamsoliman-1/ahmedamsoliman-1
  plan: free
  envVars:
  - key: CLIENT_URL
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  rootDir: docker/docker-apps/redis-commander
#################################################
- type: web
  name: aams-cvviewer-resume-dev
  runtime: docker
  repo: https://github.com/ahmedamsoliman-1/ahmedamsoliman-1
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  rootDir: apps/typescript/aams-cvviewer-resume-dev
- type: web
  name: aams-cvviewer-resume-devops
  runtime: docker
  repo: https://github.com/ahmedamsoliman-1/ahmedamsoliman-1
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  rootDir: apps/typescript/aams-cvviewer-resume-devops
- type: web
  name: aams-cvviewer-resume-dataeng
  runtime: docker
  repo: https://github.com/ahmedamsoliman-1/ahmedamsoliman-1
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  rootDir: apps/typescript/aams-cvviewer-resume-dataeng
- type: web
  name: aams-cvviewer-resume-ts
  runtime: docker
  repo: https://github.com/ahmedamsoliman-1/ahmedamsoliman-1
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  rootDir: apps/typescript/aams-cvviewer-resume-ts
- type: web
  name: aams-glinktree
  runtime: docker
  repo: https://github.com/ahmedamsoliman-1/ahmedamsoliman-1
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  rootDir: apps/go/aams-glinktree
- type: web
  name: aams-not-found
  runtime: docker
  repo: https://github.com/ahmedamsoliman-1/ahmedamsoliman-1
  plan: free
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  rootDir: apps/nodejs/not-found
version: "1"
