filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - log/*.log
      - /log/*.log
      - ./log/*.log
  - type: filestream
    id: default-filestream
    paths:
      - ingest_data/*.log

output.elasticsearch:
  hosts: ["https://172.27.89.77:9200"]
  username: SVC-logging
  password: SVCLog456$4
  ssl.certificate_authorities: ["config/certs/ca/ca.crt"]

setup.kibana:
  host: ["https://aichess-kibana-dev.avrioc.io"]
  username: SVC-logging
  password: SVCLog456$4
  ssl.certificate_authorities: ["config/certs/ca/ca.crt"]
