version: '3.9'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ../docker-volumes/db/db-data:/var/lib/postgresql/data

volumes:
  db-data:
