version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
    - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb # "host.docker.internal"
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
    ports:
    - "8081:8081"

  # mongo-express-2:
  #   image: mongo-express:latest
  #   container_name: mongo-express-2
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: mongodb
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
  #   ports:
  #   - "8082:8081"

  # mongo-express-3:
  #   image: mongo-express:latest
  #   container_name: mongo-express-3
  #   environment:
  #     ME_CONFIG_MONGODB_SERVER: localhost # "host.docker.internal"
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: "ggimdalbit"
  #   ports:
  #   - "8083:8081"


volumes:
  mongo-data:
    driver: local

# version: '3.8'
# services:
#   mongo-express:
#     image: mongo-express:latest
#     container_name: mongo-express
#     environment:
#       ME_CONFIG_MONGODB_SERVER: "host.docker.internal"
#       ME_CONFIG_MONGODB_PORT: 27017
#       ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
#       ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
#       ME_CONFIG_MONGODB_ADMINPASSWORD: "ggimdalbit"
#     ports:
#     - "8081:8081"

# volumes:
#   mongo-data:
#     driver: local
