---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.devweb.name }}-svc
  namespace: {{ .Values.devweb.namespace }}
  labels:
    app: {{ .Values.devweb.name }}-svc
spec:
  replicas: {{ .Values.devweb.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.devweb.name }}-svc
  template:
    metadata:
      labels:
        app: {{ .Values.devweb.name }}-svc
    spec:
      containers:
        - name: {{ .Values.devweb.name }}-svc
          image: {{ .Values.devweb.image.repository }}:{{ .Values.devweb.image.tag }}
          ports:
            - containerPort: {{ .Values.devweb.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.devweb.name }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.devweb.name }}-svc
  namespace: {{ .Values.devweb.namespace }}
  labels:
    app: {{ .Values.devweb.name }}-svc
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '{{ .Values.devweb.service.port }}'
spec:
  selector:
    app: {{ .Values.devweb.name }}-svc
  ports:
    - protocol: TCP
      port: {{ .Values.devweb.service.port }}
      targetPort: {{ .Values.devweb.service.port }}
  type: {{ .Values.devweb.service.type }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.devweb.name }}-config
  namespace: {{ .Values.devweb.namespace }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.devweb.name }}-ingress
  namespace: {{ .Values.devweb.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.devweb.domain.name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.devweb.name }}-svc
            port:
              number: {{ .Values.devweb.service.port }}
  tls:
  - hosts:
    - {{ .Values.devweb.domain.name }}
    secretName: {{ .Values.devweb.name }}-cert-tls
---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: {{ .Values.devweb.name }}-cert
#   namespace: {{ .Values.devweb.namespace }}
# spec:
#   secretName: {{ .Values.devweb.name }}-cert-tls
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
#   commonName: {{ .Values.devweb.domain.name }}
#   dnsNames:
#   - {{ .Values.devweb.domain.name }}
# ---