# Exported from Render on 2024-09-09T14:10:44Z
services:
- type: web
  name: aams-auth-svc
  runtime: docker
  repo: https://github.com/ahmedamsoliman-1/ahmedamsoliman-1
  plan: free
  envVars:
  - key: CLIENT_URL
    sync: false
  - key: PORT
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: MONGO_URI
    sync: false
  - key: NODE_ENV
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  rootDir: apps/typescript/auth-service
version: "1"
