apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedamsoliman-1/Tenderd-DevOps-Assignement-3.git
    targetRevision: HEAD
    path: helm-charts/frontend-svc
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedamsoliman-1/Tenderd-DevOps-Assignement-3.git
    targetRevision: HEAD
    path: helm-charts/order-svc
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedamsoliman-1/Tenderd-DevOps-Assignement-3.git
    targetRevision: HEAD
    path: helm-charts/user-svc
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
