apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ahmedamsoliman-1/ahmed.git
    targetRevision: main
    path: kubernetes/helm-charts/node-templates
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: templates
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
