filebeat.inputs:
- type: filestream
  id: redis-logs-filestream
  paths:
    - ingest_data/*.log


filebeat.autodiscover:
 providers:
   - type: docker
     hints.enabled: true


processors:
- add_docker_metadata: ~


setup.kibana:
 host: ${KIBANA_HOSTS}
 username: ${ELASTIC_USER}
 password: ${ELASTIC_PASSWORD}


output.elasticsearch:
 hosts: ${ELASTIC_HOSTS}
 username: ${ELASTIC_USER}
 password: ${ELASTIC_PASSWORD}
 ssl.enabled: true
 ssl.certificate_authorities: "certs/ca/ca.crt"
 index: "redis-logs-%{+yyyy.MM.dd}"

setup.template.name: "redis-logs"
setup.template.pattern: "redis-logs-*"
setup.template.enabled: true
