version: '3.8'

services:
  service-a:
    build:
      context: ./typescript/typescript-svcs/svc-a
    ports:
      - "3001:3001"
    depends_on:
      - service-b

  service-b:
    build:
      context: ./typescript/typescript-svcs/svc-b
    ports:
      - "3002:3002"
    depends_on:
      - service-c

  service-c:
    build:
      context: ./typescript/typescript-svcs/svc-c
    ports:
      - "3003:3003"
