version: '3.8'

services:
  portfolio:
    build:
      context: ./next-js/portfolio
      dockerfile: Dockerfile
    container_name: portfolio
    ports:
      - "8080:80"

  resume-dev-web:
    build:
      context: ./static/resume-dev-web
      dockerfile: Dockerfile
    container_name: resume-dev-web
    ports:
      - "8081:80"
  
  react-app-simple:
    build:
      context: ./react/react-app-simple
      dockerfile: Dockerfile
    container_name: react-app-simple
    ports:
      - "8082:80"
  
  frontend-svc:
    build:
      context: ./nodejs/frontend-svc
      dockerfile: Dockerfile
    container_name: frontend-svc
    ports:
      - "8083:8080"
  order-svc:
    build:
      context: ./nodejs/order-svc
      dockerfile: Dockerfile
    container_name: order-svc
    ports:
      - "8084:8080"
  user-svc:
    build:
      context: ./nodejs/user-svc
      dockerfile: Dockerfile
    container_name: user-svc
    ports:
      - "8085:8080"
  
  ahmedamsoliman-1:
    build:
      context: ./nodejs/ahmedamsoliman-1
      dockerfile: Dockerfile
    container_name: ahmedamsoliman-1
    ports:
      - "8086:8080"
  
  flask-1:
    build:
      context: ./python/flask/flask_app_1
      dockerfile: Dockerfile
    container_name: flask-1
    ports:
      - "8087:80"
  
  aams-cvviewer-resume-dev:
    build:
      context: ./typescript/aams-cvviewer-resume-dev
      dockerfile: Dockerfile
    container_name: aams-cvviewer-resume-dev
    ports:
      - "8088:3000"
  
  aams-cvviewer-resume-dataeng:
    build:
      context: ./typescript/aams-cvviewer-resume-dataeng
      dockerfile: Dockerfile
    container_name: aams-cvviewer-resume-dataeng
    ports:
      - "8089:3000"
  
  aams-cvviewer-resume-devops:
    build:
      context: ./typescript/aams-cvviewer-resume-devops
      dockerfile: Dockerfile
    container_name: aams-cvviewer-resume-devops
    ports:
      - "8090:3000"

  aams-cvviewer-resume-ts:
    build:
      context: ./typescript/aams-cvviewer-resume-ts
      dockerfile: Dockerfile
    container_name: aams-cvviewer-resume-ts
    ports:
      - "8091:3000"

  # cpp-web-app-1:
  #   build:
  #     context: ./Cpp/cppwebapp1
  #     dockerfile: Dockerfile
  #   container_name: cpp-web-app-1
  #   ports:
  #     - "8086:8080"
