
name: aams-links
namespace: aams-links

replicaCount: 2


image:
  repository: "ahmedalimsolimansd/aams-links"
  tag: "1.0.2"

service:
  type: ClusterIP
  port: 8080

domain:
  name: links.aamsd.com
