name: create-artifact

on:
  push:
    branches:
      - main

jobs:
  create-file-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create message file
      run: echo "Hello from the first workflow!" > message.txt

    - name: Upload message artifact
      uses: actions/upload-artifact@v3
      with:
        name: message-artifact
        path: message.txt
