name: create-temp-branch

on:
  push:
    branches:
      - main

jobs:
  commit-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create message file
      run: echo "Hello from the first workflow!" > message.txt

    - name: Commit file to temp branch
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git checkout -b temp-branch
        git add message.txt
        git commit -m "Add message.txt"
        git push origin temp-branch

    - name: Trigger use-temp-branch workflow
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/dispatches \
        -d '{"event_type":"use-temp-branch-trigger"}'
