name: create-artifact

on:
  push:
    branches:
      - main

jobs:
  create-file-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create message file
      run: echo "Hello from the first workflow!" > message.txt

    - name: Upload message artifact
      uses: actions/upload-artifact@v3
      with:
        name: message-artifact
        path: message.txt

    - name: Trigger use-artifact workflow
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/dispatches \
        -d '{"event_type":"use-artifact-trigger"}'
