name: use-artifact

on:
  repository_dispatch:
    types: [use-artifact-trigger]

jobs:
  download-and-use:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download message artifact
      uses: actions/download-artifact@v3
      with:
        name: message-artifact
      continue-on-error: true

    - name: List files
      run: ls -al
      continue-on-error: true

    - name: Read and display message
      run: cat message.txt
      continue-on-error: true
