name: use-temp-branch

on:
  repository_dispatch:
    types: [use-temp-branch-trigger]

jobs:
  retrieve-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout temp branch
      uses: actions/checkout@v3
      with:
        ref: temp-branch

    - name: List files
      run: ls -al

    - name: Read and display message
      run: cat message.txt

    - name: Cleanup temp branch
      run: |
        git checkout main
        git push origin --delete temp-branch
