name: 'Build CV Docker Images 2 Hub'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

env:
  ALL_PLATFORMS: linux/amd64,linux/arm64
  LATEST_TAG: '1.0.3'

jobs:
  build-push-cv-docker-images-2-hub:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: 
          - name: dev
            path: ./apps/typescript/aams-cvviewer-resume-dev
            image_name: aams-aams-cvviewer-resume-dev
          - name: devops
            path: ./apps/typescript/aams-cvviewer-resume-devops
            image_name: aams-aams-cvviewer-resume-devops
          - name: ts
            path: ./apps/typescript/aams-cvviewer-resume-ts
            image_name: aams-aams-cvviewer-resume-ts
          - name: dataeng
            path: ./apps/typescript/aams-cvviewer-resume-dataeng
            image_name: aams-aams-cvviewer-resume-dataeng

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install dependencies
        run: |
          cd ${{ matrix.app.path }}
          npm install

      - name: Build and push Docker image - ${{ matrix.app.image_name }}
        if: success()
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ matrix.app.image_name }}:${{ env.LATEST_TAG }}
          docker buildx build --platform ${{ env.ALL_PLATFORMS }} -t $IMAGE --push ${{ matrix.app.path }}
          mkdir -p output
          echo $IMAGE > output/${{ matrix.app.image_name }}.txt