name: build-cpp-project-cppnd-system-monitor

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-cpp-project-cppnd-system-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Set up CMake
      #   uses: cmake/setup-cmake@v3
      #   with:
      #     cmake-version: 3.25.0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libncurses5-dev libncursesw5-dev

      - name: Build project
        run: |
          cd apps/Cpp/CppND-System-Monitor-Project
          make build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: system-monitor-build
          path: apps/Cpp/CppND-System-Monitor-Project/build/

  # build-cpp-project-cppnd-capstone-snake-game:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     # - name: Set up CMake
  #     #   uses: cmake/setup-cmake@v3
  #     #   with:
  #     #     cmake-version: 3.25.0

  #     - name: Install dependencies
  #       run: |
  #         sudo apt update
  #         sudo apt-get install libsdl2-2.0-0
  #         sudo apt-get install libsdl2-dev
  #         sudo apt-get install libsdl2-image-dev

  #     - name: Build project
  #       run: |
  #         cd apps/Cpp/CppND-Capstone-Snake-Game
  #         make build

  #     - name: Upload build artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: snake-game-build
  #         path: apps/Cpp/CppND-Capstone-Snake-Game/build/
