name: 'Build CV Docker Images 2 Hub'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

env:
  ALL_PLATFORMS: linux/amd64,linux/arm64
  LATEST_TAG: '1.0.3'

jobs:
  build-docker-images-push-hub:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: 
          - name: frontend-svc
            path: ./apps/nodejs/frontend-svc
            image_name: aams-frontend-svc
          - name: user-svc
            path: ./apps/nodejs/user-svc
            image_name: aams-user-svc
          - name: order-svc
            path: ./apps/nodejs/order-svc
            image_name: aams-order-svc
          - name: dev-cv
            path: ./apps/typescript/aams-cvviewer-resume-dev
            image_name: aams-aams-cvviewer-resume-dev
          - name: devops-cv
            path: ./apps/typescript/aams-cvviewer-resume-devops
            image_name: aams-aams-cvviewer-resume-devops
          - name: ts-cv
            path: ./apps/typescript/aams-cvviewer-resume-ts
            image_name: aams-aams-cvviewer-resume-ts
          - name: dataeng-cv
            path: ./apps/typescript/aams-cvviewer-resume-dataeng
            image_name: aams-aams-cvviewer-resume-dataeng
          - name: ejs-auth-svc
            path: ./apps/nodejs/nodejs-ejs-auth
            image_name: aams-nodejs-ejs-auth
          - name: auth-svc
            path: ./apps/typescript/auth-service
            image_name: aams-auth-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install dependencies
        run: |
          cd ${{ matrix.app.path }}
          npm install

      - name: Build and push Docker image - ${{ matrix.app.image_name }}
        if: success()
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ matrix.app.image_name }}:${{ env.LATEST_TAG }}
          docker buildx build --platform ${{ env.ALL_PLATFORMS }} -t $IMAGE --push ${{ matrix.app.path }}
          mkdir -p output
          echo $IMAGE > output/${{ matrix.app.image_name }}.txt