name: 'Build CV Docker Images 2 Hub'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

env:
  ALL_PLATFORMS: linux/amd64,linux/arm64
  LATEST_TAG: '1.1.4'

jobs:
  typescript-build-docker-images-push-hub:
    runs-on: ubuntu-latest
    env: 
      NODE: "aams-links"
    strategy:
      matrix:

        app: 
          
          - name: aams-links
            path: ./apps/nodejs/aams-links
            image_name: aams-links
          - name: blog-app
            path: ./apps/nodejs/blog_app
            image_name: blog_app
          - name: ejs-auth-svc
            path: ./apps/nodejs/nodejs-ejs-auth
            image_name: aams-nodejs-ejs-auth
          - name: dev-cv
            path: ./apps/typescript/aams-cvviewer-resume-dev
            image_name: aams-aams-cvviewer-resume-dev
          - name: devops-cv
            path: ./apps/typescript/aams-cvviewer-resume-devops
            image_name: aams-aams-cvviewer-resume-devops
          - name: ts-cv
            path: ./apps/typescript/aams-cvviewer-resume-ts
            image_name: aams-aams-cvviewer-resume-ts
          - name: dataeng-cv
            path: ./apps/typescript/aams-cvviewer-resume-dataeng
            image_name: aams-aams-cvviewer-resume-dataeng
          - name: auth-svc
            path: ./apps/typescript/auth-service
            image_name: aams-auth-service
          - name: aams-go-linktree
            path: ./apps/go/aams-glinktree
            image_name: aams-glinktree
          - name: aams-fgallery
            path: ./apps/static/aams-fgallery
            image_name: aams-fgallery
          - name: aams-rgb-color-game
            path: ./apps/static/aams-rgb-color-game
            image_name: aams-rgb-color-game
          - name: resume-dev-web
            path: ./apps/static/resume-dev-web
            image_name: resume-dev-web
          - name: resume-dev-web2
            path: ./apps/static/resume-dev-web2
            image_name: resume-dev-web2
          - name: flask-app-1
            path: ./apps/python/flask/flask-app-1
            image_name: flask-app-1

          # - name: aams-dotnet-web-app-1
          #   path: ./apps/dotnet/aams-dotnet-web-app-1
          #   image_name: aams-dotnet-web-app-1
          # - name: resource-viewer
          #   path: ./apps/react/aams-aws-resource-viewer
          #   image_name: aams-aws-resource-viewer
          # - name: linktree-react
          #   path: ./apps/react/aams-linktree-react
          #   image_name: aams-linktree-react
          # - name: react-simple
          #   path: ./apps/react/react-app-simple
          #   image_name: react-app-simple

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image - ${{ matrix.app.image_name }}
        if: success()
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ matrix.app.image_name }}:${{ env.LATEST_TAG }}
          docker buildx build --platform ${{ env.ALL_PLATFORMS }} -t $IMAGE --push ${{ matrix.app.path }}
          mkdir -p output
          echo $IMAGE > output/${{ matrix.app.image_name }}.txt