name: 'build-push-docker-images-overleaf-hub'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: overleaf
  IMAGE_TAG: latest

jobs:
  overleaf:
    runs-on: ubuntu-latest
    # runs-on: self-managed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Install dependencies
      #   run: |
      #     cd ${{ env.FRONTEND_SVC }}
      #     npm install

      - name: Build and push Docker image
        if: success()
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker buildx build --platform linux/amd64,linux/arm64 -t $IMAGE --push ./docker/overleaf
          mkdir -p output
          echo $IMAGE > output/${{ env.IMAGE_NAME }}.txt
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ env.IMAGE_NAME }}
          path: output/${{ env.IMAGE_NAME }}.txt