name: build-cpp-projects

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-cpp-pod:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        build-system: [cmake, make]

    steps:
    - uses: actions/checkout@v4

    - name: Install CMake
      run: sudo apt-get install -y cmake
      if: matrix.os == 'ubuntu-latest'

    - name: Configure with CMake
      run: |
        cd apps/Cpp/cpp-mod
        mkdir build
        cd build
        cmake ..
        make

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v3
      with:
        name: cpp-mode-bin-${{ matrix.os }}
        path: apps/Cpp/cpp-mod/build/cpp-mode-bin