name: build-and-deploy-resume

# on: [push]
on:
    push:
      branches:
        - main

permissions:
  contents: write
jobs:
  build-and-deploy-resume:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧 
        run: |
          cd apps/static/resume-dev-pdf
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: apps/static/resume-dev-pdf