name: deploy-helm-charts

on:
  push:
    branches:
      - main

jobs:
  deploy-helm-charts-gcp2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'

    - name: Install GKE Cloud Auth plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin

    - name: Authenticate with Google Cloud
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP2_MINIFIED_CREDENTIALS }}
      run: |
        echo "${GOOGLE_APPLICATION_CREDENTIALS}" > $HOME/gcloud-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
      continue-on-error: true

    - name: Get GKE Cluster Credentials
      run: |
        gcloud container clusters get-credentials aams-gke2-gcp2-gke-primary-cluster --zone us-east1-b --project ${{ secrets.GCP2_PROJECT_ID }}
        kubectl get nodes
        kubectl get namespaces
        kubectl get pods --all-namespaces
      continue-on-error: true
    
    - name: Install Helm if not present
      run: |
        # Check if Helm is installed
        if ! helm version >/dev/null 2>&1; then
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          bash get_helm.sh
        fi
        helm version
      continue-on-error: true

    - name: Deploy/Upgrade Helm Charts - Nginx Ingress 
      working-directory: ./kubernetes/helm-charts/ingress-nginx
      run: |
        chmod +x deploy.sh
        ./deploy.sh
      continue-on-error: true

    - name: Deploy/Upgrade Helm Charts - Cert Manager 
      working-directory: ./kubernetes/helm-charts/cert-manager
      run: |
        chmod +x deploy.sh
        chmod +x deploy-cert.sh
        ./deploy.sh
        ./deploy-cert.sh
      continue-on-error: true

    - name: Delete prev ns
      run: |
        kubectl delete ns aams-node-templates
        helm delete aams-node-templates-release
        kubecl delete ingress aams-node-templates-cert-ingress -n default
      continue-on-error: true
    
    # - name: Deploy/Upgrade Helm Charts - Argo-cd with Secrets
    #   working-directory: ./kubernetes/helm-charts/your-helm-chart
    #   env:
    #     HELM_SECRET_PASSWORD: ${{ secrets.HELM_SECRET_PASSWORD }}
    #     HELM_OTHER_SECRET: ${{ secrets.HELM_OTHER_SECRET }}
    #   run: |
    #     chmod +x deploy.sh
    #     ./deploy.sh

    - name: Deploy Node Templates Helm chart
      working-directory: ./kubernetes/helm-charts/node-templates
      run: |
        chmod +x deploy.sh
        ./deploy.sh
      continue-on-error: true

    - name: Get Nodes
      run: |
        kubectl get nodes

    - name: Get Namespaces
      run: |
        kubectl get namespaces
    
    - name: Get Pods
      run: |
        kubectl get pods --all-namespaces
        
    - name: Get Servics
      run: |
        kubectl get svc --all-namespaces
    
    - name: Get Ingress
      run: |
        kubectl get ingress --all-namespaces
        
    - name: Get Certificate
      run: |
        kubectl get certificate --all-namespaces
      continue-on-error: true
    
    - name: Get Helm releaes
      run: |
        helm list --all-namespaces
      continue-on-error: true

      