name: deploy-helm-charts

on:
  push:
    branches:
      - main

jobs:
  deploy-helm-charts-gcp1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'

    - name: Install GKE Cloud Auth plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin

    - name: Authenticate with Google Cloud
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP2_MINIFIED_CREDENTIALS }}
      run: |
        echo "${GOOGLE_APPLICATION_CREDENTIALS}" > $HOME/gcloud-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json

    - name: Get GKE Cluster Credentials
      run: |
        gcloud container clusters get-credentials aams-gke2-gcp2-gke-primary-cluster --zone us-east1-b --project ${{ secrets.GCP2_PROJECT_ID }}
        kubectl get nodes
        kubectl get namespaces
        kubectl get pods --all-namespaces
    
    - name: Install Helm if not present
      run: |
        # Check if Helm is installed
        if ! helm version >/dev/null 2>&1; then
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          bash get_helm.sh
        fi
        helm version

    - name: Deploy/Upgrade Helm Charts - Nginx Ingress 
      working-directory: ./kubernetes/helm-charts/ingress-nginx
      run: |
        chmod +x deploy.sh
        ./deploy.sh
      continue-on-error: true

    - name: Deploy/Upgrade Helm Charts - Cert Manager 
      working-directory: ./kubernetes/helm-charts/cert-manager
      run: |
        chmod +x deploy.sh
        ./deploy.sh
    
    - name: Check Helm charts / Resources
      working-directory: ./kubernetes/helm-charts/cert-manager
      run: |
        kubectl get nodes
        echo "==============================================================================================================="
        echo "Namespaces: "
        kubectl get namespaces
        echo "==============================================================================================================="
        echo "Pods: "
        kubectl get pods --all-namespaces
        echo "==============================================================================================================="
        echo "SVC: "
        kubectl get svc --all-namespaces
        # echo "==============================================================================================================="
        # echo "CERTIFICATE: "
        # kubectl get certificate --all-namespaces
        echo "==============================================================================================================="
        echo "IINGRESS: "
        kubectl get ingress --all-namespaces
        echo "==============================================================================================================="
        echo "HELM CHARTS: "
        helm list --all-namespaces
      continue-on-error: true

      