name: destroy-gke-terraform

on:
  workflow_dispatch:

jobs:
  terraform-destroy-aams-gcp2-dns2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.2

    - name: Terraform Init
      working-directory: ./IasC/terraform/gcp/dns
      env:
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      run: terraform init -backend-config="token=${{ secrets.TF_API_TOKEN }}"

    - name: Terraform Destroy
      working-directory: ./IasC/terraform/gcp/dns
      env:
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      run: terraform destroy -auto-approve
