name: enable-google-cloud-apis

on:
  push:
    branches:
      - main

jobs:
  enable-google-cloud-apis-gcp1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'

    - name: Authenticate with Google Cloud
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP1_MINIFIED_CREDENTIALS }}
      run: |
        echo "${GOOGLE_APPLICATION_CREDENTIALS}" > $HOME/gcloud-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json

    - name: Set project
      run: gcloud config set project ${{ secrets.GCP1_PROJECT_ID }}

    - name: Enable Compute Engine API
      run: gcloud services enable compute.googleapis.com

    - name: Enable Kubernetes Engine API
      run: gcloud services enable container.googleapis.com

    - name: Enable IAM API
      run: gcloud services enable iam.googleapis.com

    - name: Enable Cloud Storage API
      run: gcloud services enable storage.googleapis.com
      
  enable-google-cloud-apis-gcp2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: 'latest'

    - name: Authenticate with Google Cloud
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP2_MINIFIED_CREDENTIALS }}
      run: |
        echo "${GOOGLE_APPLICATION_CREDENTIALS}" > $HOME/gcloud-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json

    - name: Set project
      run: gcloud config set project ${{ secrets.GCP2_PROJECT_ID }}

    - name: Enable Compute Engine API
      run: gcloud services enable compute.googleapis.com

    - name: Enable Kubernetes Engine API
      run: gcloud services enable container.googleapis.com

    - name: Enable IAM API
      run: gcloud services enable iam.googleapis.com

    - name: Enable Cloud Storage API
      run: gcloud services enable storage.googleapis.com
