name: Ping-Website

on:
  schedule:
    # - cron: '*/5 * * * *'
    # Runs every minute
    - cron: '* * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Ping the website
      run: |
        curl -s -o /dev/null -w "%{http_code}" https://aams-personal-cloud.onrender.com
