name: apply-terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
defaults:
  run:
    shell: bash
    working-directory: ./iac/terraform/gcp/aams-terraform-hcp
jobs:
  terraform-deploy-aams-bucket:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.2

    - name: Terraform Init
      run: pwd

    # - name: Terraform Plan
    #   run: terraform plan

    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
