name: apply-vm-terraform

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - main
defaults:
  run:
    shell: bash
    working-directory: ./IasC/terraform/gcp/vm/dev-vm-2
    
jobs:
  terraform-deploy-aams-gcp2-vm2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.2
        

    - name: Terraform Init
      env:
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      run: terraform init -backend-config="token=${{ secrets.TF_API_TOKEN }}"

    # - name: Terraform Plan
    #   env:
    #     TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    #   run: terraform plan
    
    - name: Terraform destroy
      env:
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      run: terraform destroy

    # - name: Terraform Apply
    #   if: github.event_name == 'push'
    #   env:
    #     TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
    #   run: terraform apply -auto-approve