name: upload-download-artifact

on:
  push:
    branches:
      - main

jobs:
  build-upload-download-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          mkdir -p output
          echo "Build output" > output/build.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: output/build.txt

  deploy-upload-download-artifact:
    runs-on: ubuntu-latest
    needs: build-upload-download-artifact

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact

      - name: List files
        run: ls -R

      - name: Use artifact
        run: |
          cat build.txt
